import type { GlossaryTerm } from "./types";

export const GLOSSARY: GlossaryTerm[] = [
  { id: "g1", term: "AB-410", definition: "Examen Building Intelligent Applications. Credencial Intelligent Applications Builder Associate.", domain: "intro" },
  { id: "g2", term: "Dataverse", definition: "Plataforma de datos de Power Platform: tablas, seguridad, lógica y ALM.", domain: "d1" },
  { id: "g3", term: "Prompt column", definition: "Columna cuyo valor lo genera un prompt de IA a partir de otras columnas y se persiste en la fila.", domain: "d1" },
  { id: "g4", term: "Row summary", definition: "Resumen Copilot de un registro en la ficha model-driven. No es un campo de reporte.", domain: "d1" },
  { id: "g5", term: "Solution", definition: "Contenedor de ALM. Unmanaged en DEV, managed en TEST/PROD.", domain: "d1" },
  { id: "g6", term: "Publisher prefix", definition: "Prefijo de esquema (aet_nombre) de tus componentes custom.", domain: "d1" },
  { id: "g7", term: "Environment variable", definition: "Valor de configuración por entorno, rellenado al desplegar.", domain: "d1" },
  { id: "g8", term: "Connection reference", definition: "Abstracción de una conexión para que el destino enlace la suya.", domain: "d1" },
  { id: "g9", term: "Security role", definition: "Conjunto de privilegios × nivel de acceso asignado a usuario o equipo.", domain: "d1" },
  { id: "g10", term: "Business unit", definition: "Nodo de la jerarquía de organización que delimita datos.", domain: "d1" },
  { id: "g11", term: "Hierarchy security", definition: "El manager ve registros de sus reports. Complementa roles.", domain: "d1" },
  { id: "g12", term: "Column security", definition: "Restricción a nivel de campo (salario, NIF) más allá del privilegio de tabla.", domain: "d1" },
  { id: "g13", term: "Alternate key", definition: "Clave de negocio única para upsert e integridad.", domain: "d1" },
  { id: "g14", term: "Parental relationship", definition: "Relación 1:N con cascada (delete, assign, share…).", domain: "d1" },
  { id: "g15", term: "Model-driven app", definition: "App generada desde metadata de Dataverse: forms, views, sitemap, charts.", domain: "d2" },
  { id: "g16", term: "Canvas app", definition: "App de lienzo con Power Fx, control pixel-level, móvil/tablet.", domain: "d2" },
  { id: "g17", term: "Custom page", definition: "Página canvas alojada dentro de una model-driven app.", domain: "d2" },
  { id: "g18", term: "Generative page", definition: "Custom page creada con lenguaje natural y luego revisada.", domain: "d2" },
  { id: "g19", term: "Delegation", definition: "Ejecutar el filtro/orden en el origen de datos, no en las primeras N filas locales.", domain: "d2" },
  { id: "g20", term: "Named formula", definition: "Fórmula nombrada en App.Formulas, reactiva e inmutable.", domain: "d2" },
  { id: "g21", term: "Component library", definition: "Paquete de componentes canvas reutilizables y versionados.", domain: "d2" },
  { id: "g22", term: "Monitor", definition: "Depurador en vivo de canvas: fórmulas, timings, delegación.", domain: "d2" },
  { id: "g23", term: "PCF", definition: "Power Apps Component Framework: control pro-code empaquetado.", domain: "d2" },
  { id: "g24", term: "Copilot Studio", definition: "Estudio para agentes: temas, knowledge, acciones, canales.", domain: "d2" },
  { id: "g25", term: "Power Pages", definition: "Sitios web sobre Dataverse para usuarios externos o internos anónimos/autenticados.", domain: "d2" },
  { id: "g26", term: "Cloud flow", definition: "Flujo de Power Automate en la nube: automated, instant o scheduled.", domain: "d3" },
  { id: "g27", term: "Run after", definition: "Configuración que lanza una acción según el resultado de otra (fail/success/skip/timeout).", domain: "d3" },
  { id: "g28", term: "Child flow", definition: "Flujo invocable desde otros, para reutilizar y recortar tamaño.", domain: "d3" },
  { id: "g29", term: "Approvals", definition: "Conector que crea una solicitud Approve/Reject (u otras) y espera.", domain: "d3" },
  { id: "g30", term: "AI Hub", definition: "Catálogo de prompts y modelos de IA reutilizables en el entorno.", domain: "d3" },
  { id: "g31", term: "Grounding / knowledge", definition: "Documentos o datos que condicionan al prompt para reducir alucinaciones.", domain: "d3" },
  { id: "g32", term: "Business rule", definition: "Lógica declarativa de campos (show, required, default) con scope form o entity.", domain: "d3" },
  { id: "g33", term: "Business process flow (BPF)", definition: "Barra de etapas que guía un proceso, con ramas y posible multi-tabla.", domain: "d3" },
  { id: "g34", term: "Formula column", definition: "Columna calculada con Power Fx en Dataverse.", domain: "d3" },
  { id: "g35", term: "Rollup column", definition: "Agregación asíncrona de registros hijos (SUM, COUNT, etc.).", domain: "d3" },
  { id: "g36", term: "Calculated column", definition: "Cálculo clásico de Dataverse (legado frente a formula).", domain: "d3" },
  { id: "g37", term: "DLP", definition: "Data loss prevention: políticas que restringen combinaciones de conectores.", domain: "d3" },
  { id: "g38", term: "Pipeline", definition: "Cadena de despliegue automatizada entre entornos de Power Platform.", domain: "d1" },
  { id: "g39", term: "Power Fx", definition: "Lenguaje de fórmulas de Power Platform (canvas, formula columns, comandos).", domain: "d2" },
  { id: "g40", term: "Table permissions (Pages)", definition: "Modelo de autorización de Power Pages, distinto de los security roles de apps internas.", domain: "d2" },
];
