import type { Question } from "./types";

export const Q_D1: Question[] = [
  {
    id: "q1",
    domain: "d1",
    topic: "Diseño",
    lessonId: "d1-diseno",
    difficulty: "medium",
    stem: "Contoso quiere que los empleados pregunten en lenguaje natural por políticas de gastos y, si aplica, abran un caso de reembolso en Dataverse. ¿Qué componente debes recomendar como pieza central?",
    choices: [
      "Una prompt column en la tabla Caso que redacte la política",
      "Un agente de Copilot Studio con knowledge de políticas y una acción que cree el caso",
      "Copilot del maker studio para generar una canvas app",
      "Un business process flow con una etapa por cada política",
    ],
    correct: [1],
    explanation:
      "Es un escenario de conversación + knowledge + acción. Eso es un agente. La prompt column persiste un insight de fila; el maker Copilot construye, no atiende empleados; un BPF no responde preguntas.",
  },
  {
    id: "q2",
    domain: "d1",
    topic: "Diseño",
    lessonId: "d1-diseno",
    difficulty: "easy",
    stem: "Un equipo necesita una ficha de cliente con vistas, gráficos, BPF y seguridad por unidad de negocio. ¿Qué tipo de app encaja primero?",
    choices: [
      "Canvas app en blanco",
      "Power Pages público",
      "Model-driven app sobre Dataverse",
      "Dashboard de Power BI solo",
    ],
    correct: [2],
    explanation:
      "Gestión de registros con seguridad, vistas, charts y BPF es el caso canónico de model-driven.",
  },
  {
    id: "q3",
    domain: "d1",
    topic: "Extensibilidad",
    lessonId: "d1-diseno",
    difficulty: "medium",
    stem: "La canvas necesita un control de firma manuscrita que no existe en los controles estándar. ¿Qué recomiendas?",
    choices: [
      "Una business rule que bloquee el campo Firma",
      "Un PCF empaquetado en la solución",
      "Una prompt column que describa la firma",
      "Un BPF con etapa Firma",
    ],
    correct: [1],
    explanation:
      "Cuando el control visual no existe, el siguiente escalón es PCF. El resto no pinta un canvas de firma.",
  },
  {
    id: "q4",
    domain: "d1",
    topic: "Entornos",
    lessonId: "d1-entornos-alm",
    difficulty: "easy",
    stem: "Un maker quiere practicar Dataverse y Copilot sin tocar las apps de producción de la empresa. ¿Qué entorno es el más adecuado?",
    choices: [
      "Default environment",
      "Production",
      "Developer environment",
      "El entorno de Teams de toda la compañía",
    ],
    correct: [2],
    explanation:
      "Developer incluye Dataverse y está pensado para uso individual. Default no es para desarrollo serio; Production está fuera de juego.",
  },
  {
    id: "q5",
    domain: "d1",
    topic: "Entornos",
    lessonId: "d1-entornos-alm",
    difficulty: "medium",
    stem: "El equipo de QA necesita una copia de producción con datos enmascarados que se pueda resetear. ¿Qué tipo de entorno y operación encajan?",
    choices: [
      "Sandbox con copy desde production, y reset cuando convenga",
      "Developer con export unmanaged",
      "Trial renovado cada 30 días",
      "Default environment con una solución managed",
    ],
    correct: [0],
    explanation:
      "Sandbox soporta copy y reset. Es el entorno de test clásico en ALM de Power Platform.",
  },
  {
    id: "q6",
    domain: "d1",
    topic: "ALM",
    lessonId: "d1-entornos-alm",
    difficulty: "easy",
    stem: "¿Dónde debes editar componentes día a día y cómo se despliegan a producción?",
    choices: [
      "Editar en production como unmanaged",
      "Editar en DEV unmanaged y desplegar managed a TEST/PROD",
      "Editar managed en DEV y unmanaged en PROD",
      "Trabajar siempre en Default Solution",
    ],
    correct: [1],
    explanation:
      "DEV unmanaged (fuente). TEST/PROD managed (bloqueado). Nunca Default Solution ni unmanaged en prod.",
  },
  {
    id: "q7",
    domain: "d1",
    topic: "ALM",
    lessonId: "d1-entornos-alm",
    difficulty: "medium",
    stem: "Un flujo usa una URL de API distinta en DEV y en PROD. ¿Qué artefacto de ALM debes usar?",
    choices: [
      "Una variable global de canvas Set(url, …) en OnStart",
      "Environment variable",
      "Una business rule de scope Entity",
      "El campo Description de la solución",
    ],
    correct: [1],
    explanation:
      "Environment variables existen precisamente para config que cambia por entorno. Se rellenan en el deployment.",
  },
  {
    id: "q8",
    domain: "d1",
    topic: "ALM",
    lessonId: "d1-entornos-alm",
    difficulty: "hard",
    stem: "Tras importar a TEST, los flujos fallan con error de conexión aunque en DEV iban bien. ¿Cuál es la causa más probable?",
    choices: [
      "Las prompt columns no se exportan",
      "Faltan connection references enlazadas a conexiones de TEST",
      "El publisher prefix cambió solo",
      "Solution checker no se ejecutó, y eso bloquea el runtime",
    ],
    correct: [1],
    explanation:
      "Las conexiones no viajan. Connection references deben re-enlazarse en el destino. Solution checker es calidad, no runtime.",
  },
  {
    id: "q9",
    domain: "d1",
    topic: "Dataverse",
    lessonId: "d1-dataverse",
    difficulty: "easy",
    stem: "Necesitas una tabla de «País» de solo lectura para toda la organización, sin dueño individual. ¿Qué ownership configuras?",
    choices: [
      "User or team",
      "Organization",
      "Business unit",
      "Access team",
    ],
    correct: [1],
    explanation:
      "Organization-owned: no hay owner por fila; el acceso es none u organization. Ideal para catálogos.",
  },
  {
    id: "q10",
    domain: "d1",
    topic: "Dataverse",
    lessonId: "d1-dataverse",
    difficulty: "medium",
    stem: "Al borrar un Proyecto deben borrarse sus Tareas. Si se borra un Cliente, no deben borrarse sus Pedidos: debe impedirse el borrado. ¿Qué comportamientos de relación usas?",
    choices: [
      "Ambas parental",
      "Proyecto→Tarea parental; Cliente→Pedido referential restrict delete",
      "Ambas referential remove link",
      "Proyecto→Tarea restrict; Cliente→Pedido parental",
    ],
    correct: [1],
    explanation:
      "Hijos dependientes: parental (cascade delete). Hijos que protegen al padre: restrict delete.",
  },
  {
    id: "q11",
    domain: "d1",
    topic: "Dataverse",
    lessonId: "d1-dataverse",
    difficulty: "medium",
    stem: "Quieres evitar dos cuentas con el mismo CIF al integrar desde un ERP. ¿Qué configuras?",
    choices: [
      "Duplicate detection solo",
      "Alternate key en CIF",
      "Una vista filtrada",
      "Row summary",
    ],
    correct: [1],
    explanation:
      "Alternate key = unicidad real y upsert. Duplicate detection es heurístico y no bloquea como una clave.",
  },
  {
    id: "q12",
    domain: "d1",
    topic: "Dataverse",
    lessonId: "d1-dataverse",
    difficulty: "easy",
    stem: "Prioridad (Alta/Media/Baja) se reutiliza en Caso, Tarea y Proyecto. ¿Qué tipo de choice?",
    choices: [
      "Choice local en cada tabla",
      "Choice global",
      "Yes/No",
      "Autonumber",
    ],
    correct: [1],
    explanation:
      "Choice global se comparte entre tablas. Local quedaría desincronizado.",
  },
  {
    id: "q13",
    domain: "d1",
    topic: "Prompt columns",
    lessonId: "d1-columnas-ia",
    difficulty: "medium",
    stem: "Quieres un campo Sentimiento persistido en cada Caso, visible en la vista y que un flujo pueda leer. ¿Qué usas?",
    choices: [
      "Row summary",
      "Prompt column",
      "Un chart de model-driven",
      "Una named formula de canvas",
    ],
    correct: [1],
    explanation:
      "Prompt column persiste el resultado en Dataverse. Row summary es un digest de ficha, no un campo de vista/flujo.",
  },
  {
    id: "q14",
    domain: "d1",
    topic: "Prompt columns",
    lessonId: "d1-columnas-ia",
    difficulty: "hard",
    stem: "Cambias el texto del prompt de una prompt column. Las filas antiguas no se actualizan. ¿Por qué?",
    choices: [
      "Las prompt columns nunca se recalculan",
      "Solo se regeneran al crear el registro o al cambiar una columna de input",
      "Falta publicar la model-driven app",
      "Hay que cambiar el ownership a Organization",
    ],
    correct: [1],
    explanation:
      "No hay backfill al editar el prompt. Hay que tocar un input (o crear filas nuevas). Es un límite de examen.",
  },
  {
    id: "q15",
    domain: "d1",
    topic: "Prompt columns",
    lessonId: "d1-columnas-ia",
    difficulty: "medium",
    stem: "¿Cuál NO puede usarse como input de una prompt column?",
    choices: [
      "Una columna de texto",
      "Una columna choice",
      "Otra prompt column",
      "Una columna de número",
    ],
    correct: [2],
    explanation:
      "No se permiten como input: formula, file, image u otra prompt column.",
  },
  {
    id: "q16",
    domain: "d1",
    topic: "Row summary",
    lessonId: "d1-columnas-ia",
    difficulty: "easy",
    stem: "Los agentes de mesa de ayuda quieren un resumen Copilot al abrir la ficha del caso, sin necesitar ese texto en reportes. ¿Qué configuras?",
    choices: [
      "Row summary de la tabla",
      "Cinco prompt columns",
      "Un rollup",
      "Auditing a nivel de organización",
    ],
    correct: [0],
    explanation:
      "Row summary es exactamente esa experiencia de lectura en la ficha.",
  },
  {
    id: "q17",
    domain: "d1",
    topic: "Seguridad",
    lessonId: "d1-seguridad",
    difficulty: "medium",
    stem: "Un comercial debe ver solo sus oportunidades, no las de la BU. ¿Qué nivel de Read en Opportunity?",
    choices: [
      "Organization",
      "Business Unit",
      "User",
      "Parent: Child Business Units",
    ],
    correct: [2],
    explanation:
      "User = registros que posee. BU ya le enseñaría las de sus compañeros de unidad.",
  },
  {
    id: "q18",
    domain: "d1",
    topic: "Seguridad",
    lessonId: "d1-seguridad",
    difficulty: "hard",
    stem: "Un usuario abre la model-driven app pero el grid de Casos está vacío, aunque en otra app sí ve casos. ¿Qué falta lo más probable?",
    choices: [
      "Privilegio Read de Caso o el rol no está asociado a ESTA app",
      "Una prompt column en estado Failed",
      "El entorno es Developer",
      "Falta un chart",
    ],
    correct: [0],
    explanation:
      "App access y privilegios de tabla son independientes. Puede tener la app compartida sin Read, o un rol de otra app.",
  },
  {
    id: "q19",
    domain: "d1",
    topic: "Seguridad",
    lessonId: "d1-seguridad",
    difficulty: "medium",
    stem: "El salario de un empleado debe verse solo por RR. HH. aunque otros tengan Read de la tabla Empleado. ¿Qué usas?",
    choices: [
      "Ocultar el campo con una business rule de un form",
      "Column security profile",
      "Una vista sin la columna, y nada más",
      "Organization ownership",
    ],
    correct: [1],
    explanation:
      "Business rule y vistas no son seguridad (la API seguiría leyendo). Column security sí.",
  },
  {
    id: "q20",
    domain: "d1",
    topic: "Seguridad",
    lessonId: "d1-seguridad",
    difficulty: "medium",
    stem: "Un deal team ad-hoc debe trabajar un único registro de Oportunidad sin poseerlo. ¿Qué patrón?",
    choices: [
      "Owner team que posea todas las oportunidades",
      "Access team en ese registro",
      "Cambiar ownership de la tabla a Organization",
      "Compartir la app canvas",
    ],
    correct: [1],
    explanation:
      "Access teams son para compartir un registro concreto. Owner team implica posesión.",
  },
  {
    id: "q21",
    domain: "d1",
    topic: "Auditoría",
    lessonId: "d1-seguridad",
    difficulty: "hard",
    stem: "Activaste auditing en la organización pero no ves historial del campo Teléfono. ¿Qué falta?",
    choices: [
      "Habilitar auditing también en la tabla y en la columna",
      "Un rollup sobre Teléfono",
      "Change tracking",
      "Un BPF",
    ],
    correct: [0],
    explanation:
      "Auditoría es org + tabla + columna. Change tracking es para sync, no para compliance.",
  },
  {
    id: "q22",
    domain: "d1",
    topic: "Diseño",
    lessonId: "d1-diseno",
    difficulty: "medium",
    stem: "¿Cuál es el orden de extensibilidad más alineado con AB-410?",
    choices: [
      "Plugin → PCF → flujo → configuración",
      "Configuración y low-code → conectores → custom connector / PCF → código",
      "Power Pages → Excel → plugin",
      "Siempre Copilot Studio primero",
    ],
    correct: [1],
    explanation:
      "Se empieza por lo low-code y se escala. El examen premia la opción más simple que cumple.",
  },
  {
    id: "q23",
    domain: "d1",
    topic: "ALM",
    lessonId: "d1-entornos-alm",
    difficulty: "easy",
    stem: "¿Por qué no debes desarrollar en Default Solution?",
    choices: [
      "No admite tablas",
      "Mezcla todos los componentes del sistema y no es desplegable de forma limpia",
      "Solo funciona en Teams",
      "Está siempre managed",
    ],
    correct: [1],
    explanation:
      "Default Solution es el cajón de todo el entorno. Crea tu solución y publisher.",
  },
  {
    id: "q24",
    domain: "d1",
    topic: "Dataverse",
    lessonId: "d1-dataverse",
    difficulty: "medium",
    stem: "Necesitas sincronizar incrementalmente cambios de la tabla Pedido hacia un data lake. ¿Qué propiedad de tabla habilitas?",
    choices: [
      "Auditing",
      "Change tracking",
      "Duplicate detection",
      "Row summary",
    ],
    correct: [1],
    explanation:
      "Change tracking habilita sync incremental. Auditing es historial de usuario.",
  },
  {
    id: "q25",
    domain: "d1",
    topic: "Prompt columns",
    lessonId: "d1-columnas-ia",
    difficulty: "medium",
    stem: "¿Cuál es un límite documentado de prompt columns por tabla?",
    choices: ["1", "5", "12", "Ilimitadas"],
    correct: [1],
    explanation: "Hasta 5 prompt columns por tabla. Dato típico de examen.",
  },
];
