import type { Question } from "./types";

export const Q_D2: Question[] = [
  {
    id: "q26",
    domain: "d2",
    topic: "Model-driven",
    lessonId: "d2-model-driven",
    difficulty: "easy",
    stem: "Quieres que, al crear un Caso desde un lookup, aparezca un formulario corto. ¿Qué form y qué ajuste de tabla?",
    choices: [
      "Main form y auditing",
      "Quick create form y quick create habilitado en la tabla",
      "Card form y change tracking",
      "Dashboard de sistema",
    ],
    correct: [1],
    explanation:
      "Quick create requiere el form y la opción de tabla. Es un clásico de MDA.",
  },
  {
    id: "q27",
    domain: "d2",
    topic: "Model-driven",
    lessonId: "d2-model-driven",
    difficulty: "medium",
    stem: "En la app de Agentes no debe aparecer el formulario de Supervisor de la tabla Caso, pero sí en la app de Supervisores. ¿Cómo lo modelas?",
    choices: [
      "Dos tablas Caso distintas",
      "En cada app seleccionas los forms que incluye",
      "Una business rule que borra el form",
      "Organization ownership",
    ],
    correct: [1],
    explanation:
      "La composición de la app elige forms y views. Además puedes usar form security por rol.",
  },
  {
    id: "q28",
    domain: "d2",
    topic: "Model-driven",
    lessonId: "d2-model-driven",
    difficulty: "medium",
    stem: "Necesitas un kanban de casos dentro de la model-driven, sin publicar una segunda app. ¿Qué usas?",
    choices: [
      "Custom page (o generative page) en el sitemap",
      "Power Pages anónimo",
      "Un rollup",
      "Excel Online",
    ],
    correct: [0],
    explanation:
      "Custom page = canvas dentro de la MDA. Generative pages producen ese tipo de pantalla.",
  },
  {
    id: "q29",
    domain: "d2",
    topic: "Model-driven",
    lessonId: "d2-model-driven",
    difficulty: "easy",
    stem: "Un usuario tiene privilegios de Caso pero no ve la app en el lanzador. ¿Qué falta?",
    choices: [
      "Asociar su security role a la app / compartir la app",
      "Una prompt column",
      "Habilitar auditing",
      "Crear un chart",
    ],
    correct: [0],
    explanation: "Ver datos ≠ ver la app. Falta app access.",
  },
  {
    id: "q30",
    domain: "d2",
    topic: "Generative pages",
    lessonId: "d2-generative",
    difficulty: "easy",
    stem: "¿Qué debes hacer después de generar una página con lenguaje natural?",
    choices: [
      "Nada: se publica sola a producción",
      "Revisar controles, datos y accesibilidad, publicar y añadirla a la solución",
      "Convertirla en plugin",
      "Borrar las tablas origen",
    ],
    correct: [1],
    explanation:
      "Generar es el 40%. Revisar, publicar y empaquetar es el trabajo del builder.",
  },
  {
    id: "q31",
    domain: "d2",
    topic: "Canvas",
    lessonId: "d2-canvas",
    difficulty: "medium",
    stem: "Una galería de Dataverse no muestra pedidos antiguos. Filter usa una función no delegable. ¿Cuál es el diagnóstico?",
    choices: [
      "Falta un BPF",
      "La app está trabajando solo con las primeras N filas por el límite de delegación",
      "El ownership es Organization",
      "Monitor no está instalado en el tenant",
    ],
    correct: [1],
    explanation:
      "Delegación: si no se empuja al servidor, solo ves el data row limit (500–2000).",
  },
  {
    id: "q32",
    domain: "d2",
    topic: "Canvas",
    lessonId: "d2-canvas",
    difficulty: "easy",
    stem: "Para que un lector de pantalla anuncie un icono-botón, ¿qué propiedad es esencial?",
    choices: ["Fill", "AccessibleLabel", "BorderRadius", "DelayOutput"],
    correct: [1],
    explanation: "AccessibleLabel es el skill de accesibilidad más preguntado.",
  },
  {
    id: "q33",
    domain: "d2",
    topic: "Canvas",
    lessonId: "d2-canvas",
    difficulty: "medium",
    stem: "La app se diseñó a 1366×768 con controles en X/Y fijos y en el teléfono se solapan. ¿Qué enfoque es el correcto?",
    choices: [
      "Pedir a los usuarios que usen zoom",
      "Contenedores responsive y tamaños relativos a App.Width / Height",
      "Duplicar la app por cada resolución a mano sin contenedores",
      "Pasar todo a Power Pages",
    ],
    correct: [1],
    explanation: "El study guide cita responsiveness. Contenedores, no coordenadas mágicas.",
  },
  {
    id: "q34",
    domain: "d2",
    topic: "Canvas avanzado",
    lessonId: "d2-canvas-avanzado",
    difficulty: "easy",
    stem: "Necesitas un flag local para mostrar un popup solo en la pantalla actual. ¿Qué usas?",
    choices: [
      "ClearCollect",
      "UpdateContext",
      "Un rollup",
      "Environment variable",
    ],
    correct: [1],
    explanation: "Context variable = scope de pantalla. Set sería global; collection es un conjunto.",
  },
  {
    id: "q35",
    domain: "d2",
    topic: "Canvas avanzado",
    lessonId: "d2-canvas-avanzado",
    difficulty: "medium",
    stem: "Varias canvas apps comparten el mismo header. ¿Cómo lo reutilizas con versionado?",
    choices: [
      "Copiar y pegar controles",
      "Component library",
      "Una business rule",
      "Un chart",
    ],
    correct: [1],
    explanation: "Component libraries se publican y referencian. Es el skill de reusable components.",
  },
  {
    id: "q36",
    domain: "d2",
    topic: "Canvas avanzado",
    lessonId: "d2-canvas-avanzado",
    difficulty: "medium",
    stem: "Tienes constantes y cálculos derivados (IVA, URL de ayuda) que no deben ser Set en OnStart. ¿Qué feature moderna usas?",
    choices: [
      "Named formulas (App.Formulas)",
      "Access teams",
      "Do until",
      "Quick view form",
    ],
    correct: [0],
    explanation: "Named formulas son reactivas e inmutables. El examen las nombra explícitamente.",
  },
  {
    id: "q37",
    domain: "d2",
    topic: "Canvas avanzado",
    lessonId: "d2-canvas-avanzado",
    difficulty: "medium",
    stem: "Un Patch falla a veces y la app no dice nada. ¿Qué debes implementar?",
    choices: [
      "IfError / App.OnError y Notify",
      "Parental relationship",
      "Un dashboard",
      "Change tracking",
    ],
    correct: [0],
    explanation: "Error handling es skill de canvas. Monitor ayuda a verlo en diseño.",
  },
  {
    id: "q38",
    domain: "d2",
    topic: "Canvas avanzado",
    lessonId: "d2-canvas-avanzado",
    difficulty: "easy",
    stem: "¿Qué herramienta usas para ver en vivo si una fórmula se delega y cuánto tarda?",
    choices: [
      "Solution checker solo",
      "Monitor",
      "Power BI Desktop",
      "Auditing de Dataverse",
    ],
    correct: [1],
    explanation: "Monitor es el nombre que pone el study guide.",
  },
  {
    id: "q39",
    domain: "d2",
    topic: "Agentes",
    lessonId: "d2-agentes",
    difficulty: "medium",
    stem: "Tienes una canvas de inventario y quieres un copiloto que responda «¿cuántas unidades quedan de SKU-12?» y cree un movimiento. ¿Qué haces?",
    choices: [
      "Crear un agente de Copilot Studio desde la canvas, con knowledge de las tablas y una acción de flujo",
      "Una prompt column por SKU y nada más",
      "Un BPF de 12 etapas",
      "Compartir el Excel subyacente",
    ],
    correct: [0],
    explanation:
      "Skill literal: create a Copilot Studio agent from a canvas app. Knowledge + acciones.",
  },
  {
    id: "q40",
    domain: "d2",
    topic: "Power Pages",
    lessonId: "d2-agentes",
    difficulty: "medium",
    stem: "Clientes externos deben consultar el estado de sus pedidos sin usuario interno de Power Apps. ¿Qué plataforma?",
    choices: [
      "Compartir la canvas con «Everyone»",
      "Power Pages con table permissions",
      "Default environment",
      "Un owner team",
    ],
    correct: [1],
    explanation:
      "Portales externos = Power Pages + table permissions. No se comparte una canvas interna a internet.",
  },
  {
    id: "q41",
    domain: "d2",
    topic: "Canvas",
    lessonId: "d2-canvas-avanzado",
    difficulty: "medium",
    stem: "Un botón debe lanzar un flujo y esperar un número de ticket. ¿Qué patrón?",
    choices: [
      "Flow.Run(...) con Respond to a PowerApp or flow en el flujo",
      "Un scheduled flow cada 1 minuto",
      "Business rule scope Entity",
      "Row summary",
    ],
    correct: [0],
    explanation:
      "Instant flow llamado desde canvas, con respuesta. Automate business processes from canvas apps.",
  },
  {
    id: "q42",
    domain: "d2",
    topic: "Model-driven",
    lessonId: "d2-model-driven",
    difficulty: "easy",
    stem: "Quieres un gráfico de barras de casos por prioridad en la app. ¿Dónde se define el chart?",
    choices: [
      "En la tabla Caso y luego se incluye en la app / dashboard",
      "Solo en Power BI, obligatorio",
      "En una environment variable",
      "En el publisher",
    ],
    correct: [0],
    explanation: "Charts de MDA viven en la tabla y se exponen en la app.",
  },
  {
    id: "q43",
    domain: "d2",
    topic: "Canvas avanzado",
    lessonId: "d2-canvas-avanzado",
    difficulty: "hard",
    stem: "¿Cuál es una buena razón para una user-defined function en Power Fx?",
    choices: [
      "Sustituir Dataverse",
      "Encapsular una validación o transformación reutilizada en varios controles",
      "Crear security roles",
      "Habilitar auditing",
    ],
    correct: [1],
    explanation: "UDFs = lógica reutilizable. El study guide las lista junto a named formulas y libraries.",
  },
  {
    id: "q44",
    domain: "d2",
    topic: "Model-driven",
    lessonId: "d2-model-driven",
    difficulty: "medium",
    stem: "El lookup de Cliente dentro del Caso debe mostrar teléfono y segmento sin abrir el registro. ¿Qué form?",
    choices: [
      "Quick view form",
      "Dashboard de usuario",
      "Receipt model de AI Hub",
      "Quick find view solo",
    ],
    correct: [0],
    explanation: "Quick view se incrusta en el form padre para leer el related.",
  },
  {
    id: "q45",
    domain: "d2",
    topic: "Generative pages",
    lessonId: "d2-generative",
    difficulty: "medium",
    stem: "Legal prohíbe Copilot de usuario final en el entorno de nómina. ¿Qué haces en la model-driven de RR. HH.?",
    choices: [
      "Igual incrustas un agente porque el study guide lo pide siempre",
      "Respetas la política del entorno y no habilitas Copilot/agentes en esa app",
      "Mueves la app al Default environment",
      "Conviertes salarios en prompt columns",
    ],
    correct: [1],
    explanation:
      "Gobierno e IA responsable. El builder no fuerza Copilot donde la política lo bloquea.",
  },
];
