import type { Question } from "./types";

export const Q_D3: Question[] = [
  {
    id: "q46",
    domain: "d3",
    topic: "Flujos",
    lessonId: "d3-flows",
    difficulty: "easy",
    stem: "Cuando se crea un Caso con Prioridad = Alta debe avisarse a un canal de Teams. ¿Qué trigger?",
    choices: [
      "Scheduled recurrence cada 5 minutos",
      "Dataverse When a row is added, con filtro de tabla Caso y condición de prioridad",
      "Manual button que el usuario no usará",
      "Power Apps instant sin app",
    ],
    correct: [1],
    explanation:
      "Evento de datos = automated Dataverse trigger + filtro. Recurrence es un anti-patrón.",
  },
  {
    id: "q47",
    domain: "d3",
    topic: "Flujos",
    lessonId: "d3-flows",
    difficulty: "medium",
    stem: "El flujo no se dispara al actualizar Descripción. Sí se dispara al cambiar Estado. ¿Causa típica?",
    choices: [
      "El trigger tiene «select columns» / filtro de atributos que no incluye Descripción",
      "Dataverse no soporta updates",
      "Falta un chart",
      "La app es canvas",
    ],
    correct: [0],
    explanation:
      "Filtering attributes del trigger Dataverse. Si no está la columna, no hay run.",
  },
  {
    id: "q48",
    domain: "d3",
    topic: "Flujos",
    lessonId: "d3-flows",
    difficulty: "medium",
    stem: "Si falla el envío de email, debe crearse una tarea; si el email va bien, no. ¿Cómo se configura la tarea?",
    choices: [
      "Apply to each con concurrencia 50",
      "Configure run after: has failed sobre la acción de email",
      "Do until true",
      "Un BPF",
    ],
    correct: [1],
    explanation: "Run after es el patrón de compensación. Skill de troubleshooting/control.",
  },
  {
    id: "q49",
    domain: "d3",
    topic: "Flujos",
    lessonId: "d3-flows",
    difficulty: "hard",
    stem: "Dos actualizaciones simultáneas del mismo pedido lanzan el flujo dos veces y duplican el envío a SAP. ¿Qué mitiga mejor?",
    choices: [
      "Concurrency control del trigger (grado 1) e idempotencia en la acción",
      "Quitar Dataverse",
      "Usar una canvas en lugar del flujo",
      "Row summary",
    ],
    correct: [0],
    explanation:
      "Serializar por trigger y hacer la acción idempotente. Clásico de producción.",
  },
  {
    id: "q50",
    domain: "d3",
    topic: "Conectores",
    lessonId: "d3-flows",
    difficulty: "easy",
    stem: "El cliente no tiene conectores premium y necesita leer un buzón de Office 365. ¿Qué tipo de conector?",
    choices: [
      "SQL Server premium",
      "Conector estándar de Office 365 Outlook",
      "HTTP con Azure AD (premium) obligatorio",
      "Custom connector aunque exista el estándar",
    ],
    correct: [1],
    explanation: "Evaluar conectores: usa estándar si cubre el escenario.",
  },
  {
    id: "q51",
    domain: "d3",
    topic: "Aprobaciones",
    lessonId: "d3-approvals",
    difficulty: "easy",
    stem: "Un gasto > 500 € debe ser aprobado por el manager en Teams antes de continuar. ¿Qué acción?",
    choices: [
      "Start and wait for an approval",
      "Una named formula",
      "Duplicate detection",
      "Quick create",
    ],
    correct: [0],
    explanation: "Approvals nativo. El flujo hiberna hasta la respuesta.",
  },
  {
    id: "q52",
    domain: "d3",
    topic: "Aprobaciones",
    lessonId: "d3-approvals",
    difficulty: "medium",
    stem: "Finanzas y Compliance deben aprobar ambos; si uno rechaza, se cancela. ¿Qué tipo?",
    choices: [
      "First to respond",
      "Everyone must approve",
      "Scheduled recurrence",
      "Row summary",
    ],
    correct: [1],
    explanation: "Everyone must approve encaja con «ambos». First to respond bastaría con uno.",
  },
  {
    id: "q53",
    domain: "d3",
    topic: "AI Hub",
    lessonId: "d3-ai-hub",
    difficulty: "medium",
    stem: "Los usuarios pulsan un botón «Redactar respuesta» en canvas y editan el texto antes de guardar. ¿Qué artefacto?",
    choices: [
      "Prompt column (se ejecuta sola al guardar)",
      "Prompt de AI Hub consumido desde la app",
      "Rollup",
      "Access team",
    ],
    correct: [1],
    explanation:
      "A demanda + revisión humana = prompt de AI Hub llamado por la app. Prompt column es automática y persistida.",
  },
  {
    id: "q54",
    domain: "d3",
    topic: "AI Hub",
    lessonId: "d3-ai-hub",
    difficulty: "easy",
    stem: "Hay que extraer total, fecha y proveedor de PDFs de factura con esquema estable. ¿La mejor primera opción?",
    choices: [
      "Modelo prebuilt de invoices",
      "Un BPF",
      "Choice global",
      "Hierarchy security",
    ],
    correct: [0],
    explanation:
      "Documentos conocidos → modelo prebuilt, no un prompt genérico ni lógica de app.",
  },
  {
    id: "q55",
    domain: "d3",
    topic: "AI Hub",
    lessonId: "d3-ai-hub",
    difficulty: "medium",
    stem: "Un prompt de AI Hub debe clasificar con categorías fijas y poco «creativo». ¿Qué ajuste?",
    choices: [
      "Subir al máximo la temperatura",
      "Bajar la temperatura y pedir JSON / etiqueta cerrada",
      "Quitar los inputs",
      "Mover el prompt a Default Solution",
    ],
    correct: [1],
    explanation: "Customize prompt settings: temperatura baja + formato de salida.",
  },
  {
    id: "q56",
    domain: "d3",
    topic: "AI Hub",
    lessonId: "d3-ai-hub",
    difficulty: "medium",
    stem: "El prompt alucina cláusulas que no están en la política interna. ¿Qué le añades?",
    choices: [
      "Knowledge (documentos/datos de grounding)",
      "Un chart",
      "Parental cascade",
      "Monitor de canvas",
    ],
    correct: [0],
    explanation: "Add knowledge to a prompt. Skill literal del study guide.",
  },
  {
    id: "q57",
    domain: "d3",
    topic: "AI Hub",
    lessonId: "d3-ai-hub",
    difficulty: "easy",
    stem: "Un flujo debe resumir la descripción del caso y escribir el resumen en Dataverse. ¿Dónde se consume el prompt?",
    choices: [
      "Solo en Power BI",
      "Acción de cloud flow (Run a prompt) y luego Update row",
      "En el publisher prefix",
      "En una vista pública",
    ],
    correct: [1],
    explanation: "Consume a prompt in cloud flows: acción + Patch/Update.",
  },
  {
    id: "q58",
    domain: "d3",
    topic: "Business rules",
    lessonId: "d3-rules-bpf",
    difficulty: "medium",
    stem: "El campo Motivo debe ser obligatorio siempre, incluso si el registro entra por API. ¿Scope de la business rule?",
    choices: [
      "Specific form",
      "All forms",
      "Entity (tabla)",
      "Canvas only",
    ],
    correct: [2],
    explanation:
      "Solo Entity corre en servidor y cubre API. All forms es solo UX model-driven.",
  },
  {
    id: "q59",
    domain: "d3",
    topic: "Business rules",
    lessonId: "d3-rules-bpf",
    difficulty: "easy",
    stem: "Quieres sugerir un valor de Producto sin bloquear al usuario. ¿Qué acción de rule?",
    choices: [
      "Set business required",
      "Set recommendation",
      "Lock field y hide",
      "Delete row",
    ],
    correct: [1],
    explanation: "Recommendation = bombilla, no obliga. Required sí bloquea.",
  },
  {
    id: "q60",
    domain: "d3",
    topic: "Business rules",
    lessonId: "d3-rules-bpf",
    difficulty: "medium",
    stem: "¿Qué NO puede hacer una business rule?",
    choices: [
      "Ocultar un campo en un form",
      "Llamar a SAP y esperar 2 días una aprobación",
      "Poner un valor por defecto",
      "Bloquear un campo",
    ],
    correct: [1],
    explanation: "Sin conectores ni espera. Eso es cloud flow + approvals.",
  },
  {
    id: "q61",
    domain: "d3",
    topic: "BPF",
    lessonId: "d3-rules-bpf",
    difficulty: "easy",
    stem: "Ventas debe pasar por Cualificar → Propuesta → Cierre, con campos distintos en cada etapa. ¿Qué usas?",
    choices: [
      "Business process flow",
      "Prompt column",
      "Component library",
      "Alternate key",
    ],
    correct: [0],
    explanation: "BPF = guía por etapas humanas. Skill central y a menudo subestimado.",
  },
  {
    id: "q62",
    domain: "d3",
    topic: "BPF",
    lessonId: "d3-rules-bpf",
    difficulty: "medium",
    stem: "Si el importe supera 10.000, el BPF debe ir a una etapa de Dirección. ¿Qué feature?",
    choices: [
      "Branching condicional del BPF",
      "Hierarchy security",
      "Quick find view",
      "Named formula",
    ],
    correct: [0],
    explanation: "BPF soporta ramas condicionales. No hace falta un segundo proceso.",
  },
  {
    id: "q63",
    domain: "d3",
    topic: "BPF",
    lessonId: "d3-rules-bpf",
    difficulty: "medium",
    stem: "Al entrar en la etapa Aprobación debe lanzarse un flujo de approval. ¿Cómo se enlaza?",
    choices: [
      "Cloud flow disparado por cambio de etapa / Dataverse del proceso",
      "Una vista pública",
      "El publisher",
      "Un PCF obligatorio",
    ],
    correct: [0],
    explanation:
      "BPF + flow es el patrón. El study guide habla de triggering flows on process/stage.",
  },
  {
    id: "q64",
    domain: "d3",
    topic: "Columnas lógica",
    lessonId: "d3-columnas-logica",
    difficulty: "easy",
    stem: "Quieres la suma de Importes de las líneas de un Pedido en la cabecera. ¿Qué columna?",
    choices: [
      "Rollup SUM",
      "Choice global",
      "File column",
      "Access team",
    ],
    correct: [0],
    explanation: "Agregar hijos 1:N = rollup. Un flujo que suma en cada Patch es frágil.",
  },
  {
    id: "q65",
    domain: "d3",
    topic: "Columnas lógica",
    lessonId: "d3-columnas-logica",
    difficulty: "medium",
    stem: "Un KPI de cabecera tarda horas en actualizarse tras crear líneas. ¿Por qué es esperable en un rollup?",
    choices: [
      "Los rollups son asíncronos (trabajo periódico) salvo recálculo forzado",
      "Dataverse no guarda números",
      "Falta Power Pages",
      "El rollup solo funciona en canvas",
    ],
    correct: [0],
    explanation:
      "Límite clave: asincronía. Si el escenario exige tiempo real estricto, hay que decirlo.",
  },
  {
    id: "q66",
    domain: "d3",
    topic: "Columnas lógica",
    lessonId: "d3-columnas-logica",
    difficulty: "easy",
    stem: "«Días abierto» a partir de Created On, en la misma fila. ¿La opción moderna?",
    choices: [
      "Formula column (Power Fx)",
      "Everyone must approve",
      "Virtual table",
      "PCF",
    ],
    correct: [0],
    explanation: "Cálculo intra-fila = formula (o calculated legado). No rollup.",
  },
  {
    id: "q67",
    domain: "d3",
    topic: "Decisión de lógica",
    lessonId: "d3-columnas-logica",
    difficulty: "hard",
    stem: "Hay que ocultar el campo Interno si Tipo = Público, guiar al agente por 4 etapas, y avisar a SAP al cerrar. ¿Combinación correcta?",
    choices: [
      "Un único flujo que hace las tres cosas",
      "Business rule + BPF + cloud flow",
      "Tres prompt columns",
      "Solo canvas variables",
    ],
    correct: [1],
    explanation:
      "La matriz de decisión: UX de campo = rule, etapas = BPF, sistema externo = flow.",
  },
  {
    id: "q68",
    domain: "d3",
    topic: "Flujos",
    lessonId: "d3-flows",
    difficulty: "medium",
    stem: "Un flujo supera el límite de acciones y se reutiliza desde tres procesos. ¿Qué haces?",
    choices: [
      "Child flow en una solución",
      "Pegar las acciones 3 veces",
      "Pasar a Excel",
      "Desactivar ALM",
    ],
    correct: [0],
    explanation: "Child flows = reutilización y límites. Deben vivir en solución.",
  },
  {
    id: "q69",
    domain: "d3",
    topic: "Flujos",
    lessonId: "d3-flows",
    difficulty: "medium",
    stem: "Apply to each actualiza 200 filas y a veces se pisan. ¿Qué configuras?",
    choices: [
      "Concurrencia del bucle (p. ej. 1 para secuencial) y evitar escrituras cruzadas",
      "Quitar Dataverse security",
      "Usar Default Solution",
      "Row summary en cada fila",
    ],
    correct: [0],
    explanation: "Concurrency del apply to each. Skill de control de flujo.",
  },
  {
    id: "q70",
    domain: "d3",
    topic: "AI Hub",
    lessonId: "d3-ai-hub",
    difficulty: "hard",
    stem: "¿Cuándo prefieres un modelo custom de clasificación frente a un prompt GPT?",
    choices: [
      "Cuando hay un conjunto etiquetado de casos y quieres un esquema de salida estable con confianza",
      "Cuando el usuario quiere un poema",
      "Cuando no hay datos",
      "Siempre, los prompts están prohibidos",
    ],
    correct: [0],
    explanation:
      "Custom model: entrenamiento y confianza. Prompt: flexibilidad. El examen espera el matiz.",
  },
  {
    id: "q71",
    domain: "d3",
    topic: "Aprobaciones",
    lessonId: "d3-approvals",
    difficulty: "medium",
    stem: "El registro debe mostrar Estado = Pendiente mientras Teams espera al manager. ¿Dónde actualizas el estado?",
    choices: [
      "En el flujo, antes del wait y después según Outcome",
      "Solo en una named formula",
      "No se puede",
      "En el favicon",
    ],
    correct: [0],
    explanation:
      "La app lee Dataverse. El flujo mantiene el campo de estado alrededor del approval.",
  },
  {
    id: "q72",
    domain: "d3",
    topic: "Decisión de lógica",
    lessonId: "d3-columnas-logica",
    difficulty: "hard",
    stem: "«Cada vez que se guarda el caso, rellenar un Resumen ejecutivo usable en vistas y Power BI». ¿La mejor pieza?",
    choices: [
      "Prompt column",
      "Row summary",
      "Un popup de canvas sin Patch",
      "First to respond approval",
    ],
    correct: [0],
    explanation:
      "Persistido + vistas + reportes = prompt column, no row summary (solo ficha Copilot).",
  },
  {
    id: "q73",
    domain: "d3",
    topic: "Flujos",
    lessonId: "d3-flows",
    difficulty: "easy",
    stem: "Un usuario pulsa un botón en una canvas para enviar un recordatorio ahora. ¿Tipo de flujo?",
    choices: [
      "Instant (Power Apps trigger)",
      "Recurrence cada 24 h sin botón",
      "Business rule",
      "Virtual table",
    ],
    correct: [0],
    explanation: "Instant / Power Apps. Recommend cloud flow triggers.",
  },
  {
    id: "q74",
    domain: "d3",
    topic: "Business rules",
    lessonId: "d3-rules-bpf",
    difficulty: "medium",
    stem: "Una rule de All forms oculta Descuento, pero la importación de Excel sigue metiendo descuentos. ¿Por qué?",
    choices: [
      "All forms no corre en servidor; hace falta scope Entity (o impedir el privilegio)",
      "Excel ignora Dataverse",
      "Falta un chart",
      "Las rules no se publican nunca",
    ],
    correct: [0],
    explanation: "Scope es la trampa más rentable de business rules.",
  },
  {
    id: "q75",
    domain: "d3",
    topic: "BPF",
    lessonId: "d3-rules-bpf",
    difficulty: "hard",
    stem: "El proceso de onboarding cruza Candidato y Empleado (dos tablas). ¿Puede un BPF?",
    choices: [
      "Sí, un BPF puede abarcar varias tablas en etapas sucesivas",
      "No, un BPF es de una sola tabla siempre",
      "Solo si ambas son Organization-owned",
      "Solo en Power Pages",
    ],
    correct: [0],
    explanation:
      "BPF multi-table (Lead→Opportunity, etc.). Dato de PL-200 que sigue vivo en AB-410.",
  },
];
