/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AprenderRouteImport } from './routes/aprender'
import { Route as ExamenRouteImport } from './routes/examen'
import { Route as GlosarioRouteImport } from './routes/glosario'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as PracticarRouteImport } from './routes/practicar'
import { Route as TarjetasRouteImport } from './routes/tarjetas'
import { Route as LabIdRouteImport } from './routes/lab.$id'
import { Route as LeccionIdRouteImport } from './routes/leccion.$id'
import { Route as QuizIdRouteImport } from './routes/quiz.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AprenderRoute = AprenderRouteImport.update({
  id: '/aprender',
  path: '/aprender',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamenRoute = ExamenRouteImport.update({
  id: '/examen',
  path: '/examen',
  getParentRoute: () => rootRouteImport,
} as any)
const GlosarioRoute = GlosarioRouteImport.update({
  id: '/glosario',
  path: '/glosario',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticarRoute = PracticarRouteImport.update({
  id: '/practicar',
  path: '/practicar',
  getParentRoute: () => rootRouteImport,
} as any)
const TarjetasRoute = TarjetasRouteImport.update({
  id: '/tarjetas',
  path: '/tarjetas',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIdRoute = LabIdRouteImport.update({
  id: '/lab/$id',
  path: '/lab/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LeccionIdRoute = LeccionIdRouteImport.update({
  id: '/leccion/$id',
  path: '/leccion/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/examen': typeof ExamenRoute
  '/glosario': typeof GlosarioRoute
  '/guia': typeof GuiaRoute
  '/labs': typeof LabsRoute
  '/practicar': typeof PracticarRoute
  '/tarjetas': typeof TarjetasRoute
  '/lab/$id': typeof LabIdRoute
  '/leccion/$id': typeof LeccionIdRoute
  '/quiz/$id': typeof QuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/examen': typeof ExamenRoute
  '/glosario': typeof GlosarioRoute
  '/guia': typeof GuiaRoute
  '/labs': typeof LabsRoute
  '/practicar': typeof PracticarRoute
  '/tarjetas': typeof TarjetasRoute
  '/lab/$id': typeof LabIdRoute
  '/leccion/$id': typeof LeccionIdRoute
  '/quiz/$id': typeof QuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/examen': typeof ExamenRoute
  '/glosario': typeof GlosarioRoute
  '/guia': typeof GuiaRoute
  '/labs': typeof LabsRoute
  '/practicar': typeof PracticarRoute
  '/tarjetas': typeof TarjetasRoute
  '/lab/$id': typeof LabIdRoute
  '/leccion/$id': typeof LeccionIdRoute
  '/quiz/$id': typeof QuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprender'
    | '/examen'
    | '/glosario'
    | '/guia'
    | '/labs'
    | '/practicar'
    | '/tarjetas'
    | '/lab/$id'
    | '/leccion/$id'
    | '/quiz/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprender'
    | '/examen'
    | '/glosario'
    | '/guia'
    | '/labs'
    | '/practicar'
    | '/tarjetas'
    | '/lab/$id'
    | '/leccion/$id'
    | '/quiz/$id'
  id:
    | '__root__'
    | '/'
    | '/aprender'
    | '/examen'
    | '/glosario'
    | '/guia'
    | '/labs'
    | '/practicar'
    | '/tarjetas'
    | '/lab/$id'
    | '/leccion/$id'
    | '/quiz/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprenderRoute: typeof AprenderRoute
  ExamenRoute: typeof ExamenRoute
  GlosarioRoute: typeof GlosarioRoute
  GuiaRoute: typeof GuiaRoute
  LabsRoute: typeof LabsRoute
  PracticarRoute: typeof PracticarRoute
  TarjetasRoute: typeof TarjetasRoute
  LabIdRoute: typeof LabIdRoute
  LeccionIdRoute: typeof LeccionIdRoute
  QuizIdRoute: typeof QuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprender': {
      id: '/aprender'
      path: '/aprender'
      fullPath: '/aprender'
      preLoaderRoute: typeof AprenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examen': {
      id: '/examen'
      path: '/examen'
      fullPath: '/examen'
      preLoaderRoute: typeof ExamenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glosario': {
      id: '/glosario'
      path: '/glosario'
      fullPath: '/glosario'
      preLoaderRoute: typeof GlosarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicar': {
      id: '/practicar'
      path: '/practicar'
      fullPath: '/practicar'
      preLoaderRoute: typeof PracticarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarjetas': {
      id: '/tarjetas'
      path: '/tarjetas'
      fullPath: '/tarjetas'
      preLoaderRoute: typeof TarjetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$id': {
      id: '/lab/$id'
      path: '/lab/$id'
      fullPath: '/lab/$id'
      preLoaderRoute: typeof LabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leccion/$id': {
      id: '/leccion/$id'
      path: '/leccion/$id'
      fullPath: '/leccion/$id'
      preLoaderRoute: typeof LeccionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprenderRoute: AprenderRoute,
  ExamenRoute: ExamenRoute,
  GlosarioRoute: GlosarioRoute,
  GuiaRoute: GuiaRoute,
  LabsRoute: LabsRoute,
  PracticarRoute: PracticarRoute,
  TarjetasRoute: TarjetasRoute,
  LabIdRoute: LabIdRoute,
  LeccionIdRoute: LeccionIdRoute,
  QuizIdRoute: QuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
